server:
  port: 18502
spring:
  application:
    name: xst-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.198.128:5608/xydmall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  jackson:
    #日志格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #决定返回的日期是否会被转换为时间戳，该属性默认为true，不配置该属性默认返回时间戳
      write-dates-as-timestamps: false
# mybatis-plus相关配置
mybatis-plus:
  # 以下配置均有默认值,可以不设置
  mapper-locations: classpath:com/edu118/commodity/dao/mapper/*.xml
  #config-location: classpath:com/edu118/commodity/dao/mapper/mybatis.cfg.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #关闭二级缓存
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto       #主键生成策略
      table-prefix: pms_  #表前缀
logging:
  level:
    com.edu118.dao: debug
